### ISSUE TITLE
Application crash on window resize

### ISSUE THREAD

**Issue by SzyJ** [Untitled-Games/Vulkan-Pipeline-Assistant#16]
To replicate:
Resize the window to be bigger than the default.

Error message:
QVulkanWindow: Device lost

**Comment by SzyJ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #16](https://trello.com/c/XHgyojrY/51-issue-16)

**Comment by Qozul** [comment]
This should be fixed with the latest vulkancore commit
