### ISSUE TITLE
Application crash on minimise and unminimise

### ISSUE THREAD

**Issue by SzyJ** [Untitled-Games/Vulkan-Pipeline-Assistant#17]
To replicate:
- Start app.
- Minimise window
- Re-open window by clicking on the taskbar.

Error:
vulkanrenderer.cpp -> VPA_VKCRITICAL_PASS call.
linkely to be with vkCreateFrameBuffer using a invalid device.

**Comment by SzyJ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #17](https://trello.com/c/sMZwua4j/52-issue-17)

**Comment by Qozul** [comment]
Fixed in last vulkancore merge
